server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: booths
            uri: http://localhost:8090
            predicates:
              - Path=/api/Booths/**
          - id: exhibitors
            uri: http://localhost:8070
            predicates:
              - Path=/exhibitor/api/Exhibitors/**
<<<<<<< HEAD
          - id: Appointement
            uri: http://localhost:8095
            predicates:
              - Path=/api/AppointementAndClassrooms/**


=======
          - id: events
            uri: http://localhost:8091
            predicates:
            - Path=/api/Event/Events/**
>>>>>>> 6f932ffb00ce51a891d0ec57ed7f466bb9f56792




eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/