server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: booths
            uri: http://localhost:8763
            predicates:
              - Path=/api/BoothAndSupplier/**
            filters:
              - AuthenticationFilter
          - id: suppliers
            uri: http://localhost:8763
            predicates:
              - Path=/api/supplyrequest/**
            metadata:
              cors:
                allowedOrigins: '*'
                allowedMethods:
                  - GET
                  - POST
                allowedHeaders: '*'
                maxAge: 30
            filters:
              - AuthenticationFilter
          - id: exhibitors
            uri: http://localhost:8070
            predicates:
              - Path=/exhibitor/api/BoothAndSupplier/**
          - id: AuthenticationService
            uri: http://localhost:8080
            predicates:
              - Path=/auth/**

    discovery:
        locator:
          enabled: true





eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/