server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: booths
            uri: http://localhost:8763
            predicates:
              - Path=/api/BoothAndSupplier/**
            filters:
              - AuthenticationFilter
          - id: suppliers
            uri: http://localhost:8763
            predicates:
              - Path=/api/supplyrequest/**
            metadata:
              cors:
                allowedOrigins: '*'
                allowedMethods:
                  - GET
                  - POST
                allowedHeaders: '*'
                maxAge: 30
            filters:
              - AuthenticationFilter
          - id: supplyoffer
            uri: http://localhost:8763
            predicates:
              - Path=/api/SupplyOffer/**
            metadata:
              cors:
                allowedOrigins: '*'
                allowedMethods:
                  - GET
                  - POST
                allowedHeaders: '*'
                maxAge: 30
            filters:
              - AuthenticationFilter
          - id: authservice
            uri: http://localhost:8099
            predicates:
              - Path=/auth/**
            metadata:
              cors:
                allowedOrigins: '*'
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders: '*'
                maxAge: 30
            filters:
              - AuthenticationFilter
          - id: exhibitors
            uri: http://localhost:8070
            predicates:
              - Path=/exhibitor/api/Exhibitors/**
          - id: rooms
            uri: http://localhost:8083
            predicates:
              - Path=/api/rooms/**
            metadata:
              cors:
                allowedOrigins: '*'
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders: '*'
                maxAge: 30
            filters:
              - AuthenticationFilter
          - id: packs
            uri: http://localhost:8083
            predicates:
              - Path=/api/packs/**
            metadata:
              cors:
                allowedOrigins: '*'
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders: '*'
                maxAge: 30
            filters:
              - AuthenticationFilter




eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/