eureka:
  instance:
    hostname: localhost
  client:
    eureka-service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8060
# DATABASE
spring:
  application:
    name: GestionUser

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test12348?createDatabaseIfNotExist=true
    hikari:
      username: root
      password:
  # JPA / HIBERNATE

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000



# Mailing
mailing:
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: siki.mdm@gmail.com
      password: uujtoekvvvctgxsq
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enabled: true

