eureka:
  instance:
    hostname: localhost
  client:
    eureka-service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8060
# DATABASE
spring:
  application:
    name: Gestion_User
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/test12348?createDatabaseIfNotExist=true
    username: root
    password:
  # JPA / HIBERNATE
  datasource.driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  # Enable spring data repos
  data:
    jpa:
      repositories:
        enabled: true


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000



# Mailing
mailing:
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: siki.mdm@gmail.com
      password: uujtoekvvvctgxsq
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enabled: true

