spring:
  application:
    name: Claim
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: salma.saidi@esprit.tn
    password: "xafr ccgm lqqi dzal"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
