
spring:
  application:
    name: Offer
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    username: anasmag15@gmail.com
    password: eyhndpckteehfquh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


